version: '3.8'

services:
  f1_postgres:
    image: postgres:15
    container_name: f1_dwh_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: f1_dwh
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: unless-stopped